In [20]:
#nicer display of tables
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [1]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


In [ ]:
import pandas as pdb

df = pd.DataFrame({
          'A':['a','b','a'],
          'B':['b','a','c']
        })
df
Out[]: 
   A  B
0  a  b
1  b  a
2  a  c

# Get one hot encoding of columns B
one_hot = pd.get_dummies(df['B'])
# Drop column B as it is now encoded
df = df.drop('B',axis = 1)
# Join the encoded df
df = df.join(one_hot)
df  
Out[]: 
       A  a  b  c
    0  a  0  1  0
    1  b  1  0  0
    2  a  0  0  1

https://stackoverflow.com/questions/37292872/how-can-i-one-hot-encode-in-python

https://blog.cambridgespark.com/robust-one-hot-encoding-in-python-3e29bfcec77e

In [10]:
import pandas as pd

df = pd.DataFrame([["London", "car", 20],
                   ["Cambridge", "car", 10],
                   ["Liverpool", "bus", 30]],
                  columns=["city", "transport", "duration"])
                  
df_test = pd.DataFrame([["Manchester", "bike", 30], 
                        ["Cambridge", "car", 40], 
                        ["Liverpool", "bike", 10]], 
                       columns=["city", "transport", "duration"])

In [13]:
#columns to process
cat_columns = ["city", "transport"]

In [21]:
df
df_test

city transport  duration
0     London       car        20
1  Cambridge       car        10
2  Liverpool       bus        30

city transport  duration
0  Manchester      bike        30
1   Cambridge       car        40
2   Liverpool      bike        10

In [12]:
df_processed = pd.get_dummies(df, prefix_sep="__",
                              columns=cat_columns)

In [14]:
cat_dummies = [col for col in df_processed 
               if "__" in col 
               and col.split("__")[0] in cat_columns]

In [15]:
processed_columns = list(df_processed.columns[:])

In [16]:
df_test_processed = pd.get_dummies(df_test, prefix_sep="__", 
                                   columns=cat_columns)

In [17]:
df_test_processed

duration  city__Cambridge  city__Liverpool  city__Manchester  \
0        30                0                0                 1   
1        40                1                0                 0   
2        10                0                1                 0   

   transport__bike  transport__car  
0                1               0  
1                0               1  
2                1               0

In [25]:
for col in cat_dummies:
    if col not in df_test_processed.columns:
        print("Adding missing feature {}".format(col))
        df_test_processed[col] = 0

In [26]:
df_test_processed = df_test_processed[processed_columns]

In [27]:
df_test_processed

duration  city__Cambridge  city__Liverpool  city__London  transport__bus  \
0        30                0                0             0               0   
1        40                1                0             0               0   
2        10                0                1             0               0   

   transport__car  
0               0  
1               1  
2               0